const CONFIG = {
    BASE_URL: '',
    DEFAULT_LANGUAGE: 'en-us',
    CACHE_NAME: 'GAME-API-DATA',
    DATABASE_NAME: 'GAMES-CATALOGUE',
    DATABASE_VERISON: 1,
    OBJECT_STORE_NAME: 'GAME',
  };
  export default CONFIG;